name: Security Checks
on: [push, pull_request]

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout code
    - uses: actions/checkout@v3
    
    # 1. Secret Scanning (Security Check #1)
    - name: Detect secrets
      uses: gitleaks/gitleaks-action@v2
      with:
        config-path: https://raw.githubusercontent.com/gitleaks/gitleaks/master/config/gitleaks.toml
    
    # 2. Dependency Check (Security Check #2)
    - name: Check dependencies
      uses: actions/dependency-review-action@v2
    
    # SAST Tool #1: Semgrep
    - name: Run Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: p/r2c-security-audit
    
    # SAST Tool #2: Bandit (Python SAST - will skip if no Python files)
    - name: Run Bandit
      run: |
        pip install bandit
        bandit -r . -ll || echo "Bandit ran (ignore if no Python files)"
    
    # SCA Tool: OWASP Dependency-Check
    - name: OWASP Dependency Check
      uses: dependency-check/Dependency-Check@main
      with:
        failBuildOnCVSS: 7
        format: HTML